### ISSUE TITLE
Add weights to the distance function?

### ISSUE THREAD

**Issue by simonschmeisser** [marip8/sampling_kinematics_plugin#3]
https://github.com/marip8/sampling_kinematics_plugin/blob/9e57dcc2ed13144189b14edc537badb0f16c624c/sampling_kinematics_plugin/src/external_axis_sampling_kinematics_plugin.cpp#L15

I wonder if it is necessary to add weights here in order to use the rail less/more often? Admittedly I have no idea how the speed of rails compares to the speed of normal robot axes ...

**Comment by gavanderhoorn** [comment]
Yes, this would be good to add.

If only to account for the difference in units between linear rails and revolute joints.

**Comment by marip8** [comment]
Closing, as this was addressed in #7. @simonschmeisser thanks for the suggestion
